INITIAL_VIDEO_WIDTH = 960
INITIAL_VIDEO_HEIGHT = 960
INITIAL_VIDEO_RATIO = INITIAL_VIDEO_WIDTH / INITIAL_VIDEO_HEIGHT

FINAL_VIDEO_PANEL_WIDTH = 1080
FINAL_VIDEO_PANEL_HEIGHT = 960

FINAL_VIDEO_WIDTH = FINAL_VIDEO_PANEL_WIDTH
FINAL_VIDEO_HEIGHT = FINAL_VIDEO_PANEL_HEIGHT * 2
FINAL_VIDEO_TEXT_FONT_SIZE = 60
FINAL_VIDEO_BITRATE = '2000k'
FINAL_VIDEO_FPS = 30
FINAL_VIDEO_THREADS = 4
FINAL_VIDEO_PRESET = 'ultrafast'

